version: '3'
services:
  front-react:
    build:
      context: ./client
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - type: bind
        source: D:/freshcode/module-8/lectures/pe2023-1-practice-project-main/client
        target: /client
      - /client/node_modules
    ports:
      - "5000:3000"

  server-dev:
    build:
      context: ./server
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - type: bind
        source: D:/freshcode/module-8/lectures/pe2023-1-practice-project-main/server
        target: /server
      - /server/node_modules
    ports:
      - "3000:3000"

  mongo-dev:
    image: mongo:4.4.6-bionic
    ports:
      - "27027:27017"

  db-dev:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-dev
    ports:
      - "2345:5432"