### 200
GET http://localhost:5000/users/id/transactions?limit=10&offset=0 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJjcmVhdGl2ZWZuIiwidXNlcklkIjo1LCJyb2xlIjoiY3JlYXRvciIsImxhc3ROYW1lIjoiY3JlYXRpdmVsbiIsImF2YXRhciI6ImFub24ucG5nIiwiZGlzcGxheU5hbWUiOiJjcmVhdGl2ZWRuIiwiYmFsYW5jZSI6IjEwMCIsImVtYWlsIjoiY3JlYXRpdmVAZ21haWwuY29tIiwicmF0aW5nIjowLCJpYXQiOjE3NTA1MDI3MjgsImV4cCI6MTc1MDUwNjMyOH0.vUCPy_MIl-hYI2bOotd7qy-Lo5ijs2FFOIw4kgCCqOs